### ISSUE TITLE
Settings gone after restart

### ISSUE THREAD

**Issue by justinkruit** [Kwoth/NadekoBot#882] opened 2016-12-11 14:28 UTC
For example, when I do ".antispam 3 mute" it works fine, but after I do a restart of the bot, that setting has been removed again. Same goes for the location of .logserver. I set it in a particular Channel, but after a restart, it starts putting it all in the General channel again.

**Comment by samdivaio** [comment] 2016-12-12 01:28
Log server should persist after the bot restarts as its settings are saved in DB file and I don't think functions like antispam and slowmodes work that way they do reset after restarting the bot.

**Comment by Kwoth** [comment] 2016-12-12 04:06
anti* commands do not persist restarts. I can't reproduce the lgoserver bug, and it's currently being redone, closing this.

**Closed by Kwoth** 2016-12-12 04:06 UTC
