### ISSUE TITLE
.fairplay

### ISSUE THREAD

**Issue by Devaliah** [Kwoth/NadekoBot#2054] opened 2018-02-04 15:51 UTC
`.fairplay` sometimes glitches out, and resets the playlist from the beginning,  replaying all previous songs before any of the "fairplay" songs.

**Comment by Macley-Kun** [comment] 2018-02-04 15:52
Hey the music issues actully go here:
https://github.com/Kwoth/NadekoBot/issues/1053
Could you re-ask it there and close his one?

**Comment by Kwoth** [comment] 2018-02-05 07:53
duplicate of #1389

**Closed by Kwoth** 2018-02-05 07:53 UTC
