### ISSUE TITLE
.send formatting is broken

### ISSUE THREAD

**Issue by d-floe** [Kwoth/NadekoBot#2061] opened 2018-02-05 18:55 UTC
The .send command keeps trying to format it as a quote for some reason
![image](https://user-images.githubusercontent.com/31980883/35823080-ebe22842-0a73-11e8-85f3-9ad3cda39729.png)

**Comment by shikhir-arora** [comment] 2018-02-05 18:59
Hm, it was changed a few days ago by Kwoth to support embeds; looks like the code also shows that formatting. Not sure what the intent is though. Will defer to @Kwoth

**Comment by Kwoth** [comment] 2018-02-05 19:09
woopsy daisy.

**Comment by Kwoth** [comment] 2018-02-05 19:11
Fixed in 2.14.2

**Comment by Devaliah** [comment] 2018-02-05 19:12
looks like it. I think kwoth intended the megaphone as a kinda... announcement thing? Personally i don't like it as it takes away some creativity if you wanna add a custom emote in front of it. I can confirm the weird double send in code. embeds seem to be formatted correctly.

**Closed by Kwoth** 2018-02-05 19:11 UTC
