### ISSUE TITLE
Logging Bug

### ISSUE THREAD

**Issue by fjrichman** [Kwoth/NadekoBot#265] opened 2016-05-04 19:38 UTC
NadekoBot seems to randomly stop logging with no notification or warning that it is doing so.

**Comment by Kwoth** [comment] 2016-05-04 19:42
She stops logging when you restart the bot.

**Comment by fjrichman** [comment] 2016-05-04 19:47
In this case the bot has not be restarted by me but logging has stopped.

**Comment by xnaas** [comment] 2016-05-04 23:19
Happens to me too. Have to restart logging once a day worst case scenario. But I'll check and the uptime can still be 4+ days.

**Comment by samdivaio** [comment] 2016-05-12 11:48
I can confirm to that, the strange thing is, it doesn't stop universally, so it's more like Discord server issue, because I have seen it with logging few servers and it just stops working (more like getting disabled) after a while for 1/3 servers. So the possible workaround it making .logserver append to config.json and make it work even after bot restart and an independent command to stop logserver like `.logstop`

**Comment by Kwoth** [comment] 2016-07-04 06:52
Pretty sure this should be fixed in the upcoming release. Logserver,userpresnce and voicepresence will persist restarts so i don't see how they could get reset now.

**Closed by Kwoth** 2016-07-04 06:52 UTC
Labels: bug
