### ISSUE TITLE
Crashes On Startup

### ISSUE THREAD

**Issue by lukes312** [Kwoth/NadekoBot#1775] opened 2017-10-29 04:54 UTC
I tried setting up the nadekobot and when I went to start it i got this error. I tried messing with the credentials, as its suggesting a error with coding and over 2 hours ive got no where.

___________________________________________________________________________________________________________
 00:53:45 BotCredentials | Unsupported JSON token 'EndObject' was found. Path '', line 23 position 1.
00:53:45 BotCredentials | System.FormatException: Unsupported JSON token 'EndObject' was found. Path '', line 23 position 1.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at NadekoBot.Core.Services.Impl.BotCredentials..ctor()

Unhandled Exception: System.FormatException: Unsupported JSON token 'EndObject' was found. Path '', line 23 position 1.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at NadekoBot.Core.Services.Impl.BotCredentials..ctor()
   at NadekoBot.Core.Services.ShardsCoordinator..ctor()
   at NadekoBot.Program.Main(String[] args)
   at NadekoBot.Program.<Main>(String[] args)
____________________________________________________________________________________________________________

and then it will force close and leave me frustrated

**Comment by Kuromaru420** [comment] 2017-10-29 05:11
Open up credentials.json and check line 23. You might be missing/have an extra quotation mark or bracket.
Example:
![cred](https://user-images.githubusercontent.com/15279414/32140848-93ebd6d0-bc6f-11e7-830d-ee1031915ace.png)

**Comment by Macley-Kun** [comment] 2017-11-07 06:33
@lukes312 did this solved your issue?

**Comment by Macley-Kun** [comment] 2017-11-16 10:52
@Kwoth @lukes312 think it's safe to say the issue is solved :-) close this s.v.p.~~~

**Closed** 2017-11-16 12:07 UTC
Labels: question
