### ISSUE TITLE
NadekoBot Updater not launching

### ISSUE THREAD

**Issue by Jengas** [Kwoth/NadekoBot#1663] opened 2017-09-30 21:34 UTC
Finally after few hours of trying to get some logs, i got it by deleting in programs "Nadeko Updater". Developers, please help me out.
P.S Windows Server 2016

Screen Shot - http://prntscr.com/grplec
Logs - https://pastebin.com/sE4aNfnb

P.S.S Even if it will be downloaded, it still not launching

**Comment by Kwoth** [comment] 2017-09-30 21:37
Try running it as admin. Something is blocking your access to that website.

**Comment by Jengas** [comment] 2017-09-30 21:39
Same error

**Comment by Kwoth** [comment] 2017-09-30 21:46
Something is blocking your app, or access to that website. Could be your antivirus, could be your server settings. Could be bitdefender.

Updater is working fine for the most people.

**Comment by Jengas** [comment] 2017-10-01 09:09
Website works. http://prntscr.com/grud5t
Antivirus off. http://prntscr.com/grudpi
No bitdefender.
Which server settings?

**Comment by Kwoth** [comment] 2017-10-01 11:39
I would say google the error you've got

`URLDownloadToCacheFile failed with HRESULT '-2146697208'`

**Comment by xnaas** [comment] 2017-10-01 12:23
Is this a dupe of #1648? 🤔

**Closed** 2017-10-01 14:50 UTC
Labels: question
