### ISSUE TITLE
Stutter in music

### ISSUE THREAD

**Issue by LunarSera** [Kwoth/NadekoBot#1803] opened 2017-11-06 01:50 UTC
With nadeko version 2.3.5 I noticed that when I send .xp , selfhosted  nadeko stutters in the music once,
I'm not sure how long this has been an issue, but I just noticed it.

**Comment by MaybeGoogle** [comment] 2017-11-06 02:24
That makes sense. The xp card is a picture, so when you use `.xp` your computer sends out a relatively large upload. The only fix for this without changing nadekobot would be to get faster upload speeds...

**Comment by LunarSera** [comment] 2017-11-06 02:28
Would be a good response, if I wasnt using digital ocean. Not sure how that affects it

**Comment by shikhir-arora** [comment] 2017-11-06 03:15
You likely need a bit more memory. Xp uses redis which is a memory-based store, it is very fast but it does use memory. If there’s a lack of resources for a second when the command is issued then that is likely the cause. Digital Ocean have excellent network speeds so I don’t think that is of concern.

**Comment by Kwoth** [comment] 2017-11-06 03:21
Music is extremely sensitive to network and cpu usage. Is someone experiencing this on their own bot on a dedicated server? I've been told in discord.net 3.0 I will be able to hook up my own music thing, instead of using built in discord.net one. This should help a lot. For now just use #1053

**Closed by Kwoth** 2017-11-06 03:21 UTC

**Comment by shikhir-arora** [comment] 2017-11-07 00:16
@Kwoth admittedly I don't really use Nadeko's music anymore, but I never had this issue on a powerful dedicated server. I think this specific users case was a lack of memory, probably due to the `.xp` and Redis memory usage.

**Comment by LunarSera** [comment] 2017-11-07 00:18
I wouldn't have submitted it if it wasn't a new issue. I had no glitches with music a week ago. I don't know what change made it stutter. but I've used music consistently for over 3 months now. this is the first time in a long time I've had this happen.

**Comment by LunarSera** [comment] 2017-11-07 00:22
I know that previously queueing songs made it stutter. that was fixed with a new core of the music module. I agree xp could be an issue, but as I've said, nothing new has occurred. and my hot is part of three very active servers. one of them rolls through a good 150 messages a minute with 10 commands in that minute.... if they aren't spamming gambling commands. my point is I don't think it's the dedicated server I run Nadeko on but I'm open to opinions. just some more facts for you guys.

**Comment by shikhir-arora** [comment] 2017-11-07 00:42
> With nadeko version 2.3.5 I noticed that when I send .xp , selfhosted nadeko stutters in the music once,

Are you sure it didn't stutter on 1.9+ *when* you used the `.xp` module? No changes were made recently to the Music Module. The fact that it stutters on `.xp` specifically leads me to think it's a memory issue.

Type `free -m` while doing these commands in your console for your dedicated server. Also, if you want, type: `ps aux | grep ffmpeg` while you are experiencing these issues and post the screenshot (again, on your console for the dedicated server)
