### ISSUE TITLE
Bot after youtube-dl update will not display Japanese/Chinese characters in song information.

### ISSUE THREAD

**Issue by OrigamiSS** [Kwoth/NadekoBot#1366] opened 2017-07-09 02:09 UTC
After the new update the now playing and queue list will show random symbols instead of actual characters . This is repeatable only on windows version of Nadeko bot.

https://cdn.discordapp.com/attachments/330949870816854027/333397973847375873/image.png

**Comment by ManuelFte** [comment] 2017-07-09 02:12
In my case, the Windows install ignores any non-Latin character (meaning a song with only Japanese/Chinese characters in the title will appear as having no name). The Linux version doesn't have this issue.

**Comment by Kwoth** [comment] 2017-07-10 18:13
I actually have no idea how to solve this.

**Comment by samdivaio** [comment] 2017-07-12 04:07
python issue? https://github.com/rg3/youtube-dl/issues/13185

**Comment by willysunny** [comment] 2017-09-04 08:20
Just a heads up, I can NOT reproduce it on docker with Nadeko V1.7.1 anymore. So youtube-dl might have fixed it themselves?

**Comment by samdivaio** [comment] 2017-09-04 09:37
NadekoBot 1.5.1 doesn't even use YouTube-dl, its introduced with version 1.54a I guess.
Also the issue is related to Python and it can be easily fixed on linux https://github.com/Kwoth/NadekoBot/issues/1392 docker already uses the locale required.

**Comment by Macley-Kun** [comment] 2017-09-11 14:03
So can we confirm that the issue is still present lads? If it's fixed then i geuss the issue is no longer relevant.

**Comment by Kwoth** [comment] 2017-09-11 17:54
it is

**Comment by Macley-Kun** [comment] 2017-09-16 19:31
I suggest we could add the help wanted label on this? Maybe someone knows how to resolve this!

**Comment by Macley-Kun** [comment] 2017-09-19 14:23
Because we need a similar answer in: #1455.
I'll mention the issue on both, so if someone would be able to help, he/she can also help with the other issue.

**Comment by willysunny** [comment] 2017-09-26 01:44
So ... correct me if I'm wrong. So basically this is just a local issue?

But I don't see a locale-gen in youtube-dl for windows version?

**Comment by Macley-Kun** [comment] 2017-11-30 17:26
Correct me if i'm wrong. But the youtube-dl isn't something Kwoth can edit/change right? Wouldn't it be better to open an issue on Youtube-dl Github? We could then refer to that issue from here and then close this one (or close it when they add support for it).

**Comment by Kwoth** [comment] 2018-03-07 10:01
I think it should work, as youtube-dl is only used as a fallback now.

**Closed by Kwoth** 2018-03-07 10:01 UTC
Labels: bug, help wanted
