### ISSUE TITLE
NadekoBot mobile website not working with firefox

### ISSUE THREAD

**Issue by Taknok** [Kwoth/NadekoBot#2207] opened 2018-04-01 21:02 UTC
The last website update introduce a mobile version, and it's working fine on android with chrome, but when using firefox 59.0.2 it's only show a black page.

Not sure if the issue has to be posted on this repo, but I didn't find any repo for the website...

Edit : even firefox 59.0.2 on computer isn't working now (and did in the past)

Edit 2 : Firefox in safe mode gives the same result

**Comment by Macley-Kun** [comment] 2018-04-01 21:18
Repo of website is set to private.
Thanks for reporting the bug!

**Comment by Kwoth** [comment] 2018-04-02 06:53
I'm using 59.0.2 and it works for me.

**Comment by Taknok** [comment] 2018-04-02 11:53
I tried the safe mode on computer and it's working, the issue is triggered by adblock. I made a ticket to white-list your website :)
So I don't know if it's your new mobile version or an update in the lists of adblock that brings the issue :/

**Comment by xnaas** [comment] 2018-04-02 14:15
It's because any blocking tool is going to see anything trying to mine in your browser as malicious, which is the correct way to handle it. At least, that's what I'm assuming the `authedmine.min.js` is related too, I'm too lazy to check. 😜 

So I guess "issue resolved" since you've simply whitelisted it and it's working, yeah?

**Comment by Taknok** [comment] 2018-04-02 15:34
Yes, `authedmine.min.js` is for mining. But I don't see why this script is loaded in the main page when you are not logged or if you haven't toggle on mining :/ It's strange because I haven't issue with the website until 2 days ago. At least blocking the script should not block the full rendering of the webpage and just display an error message in a corner for miners (it's nor urgent, but it would be great).

I fully agree with your edit point ;)

**Comment by Macley-Kun** [comment] 2018-04-03 18:11
@Taknok you can close the issue is what Xnaas was refering too 😛

**Closed** 2018-04-03 18:13 UTC
Labels: question
