### ISSUE TITLE
Music not working from youtube

### ISSUE THREAD

**Issue by borgqueenx** [Kwoth/NadekoBot#1559] opened 2017-09-05 11:42 UTC
I am running centos 7 with latest youtube-dl and ffmpeg 3.3.2.
I am getting the following error when wanting to play a song:
https://puu.sh/xs3Ax/f94c495b8a.png

Doesn't matter what youtube song. The bot joins, does nothing and disconnects from the voice channel.

Help would be appriciated!

**Comment by Kwoth** [comment] 2017-09-05 12:05
duplicate of #1308

**Closed by Kwoth** 2017-09-05 12:05 UTC
