### ISSUE TITLE
.masskill fails to ban targeted users

### ISSUE THREAD

**Issue by zergling-man** [Kwoth/NadekoBot#2011] opened 2018-01-17 10:49 UTC
In a live test, three targeted users were not banned, unknown if they were actually blacklisted. No errors were reported to channel.
In a controlled test, two users were successfully banned (bot accounts), but a third (user, with admin rights + higher role) was not banned, with an HTTP 403 error in console; nor were they blacklisted. No errors were reported to channel.

**Comment by Macley-Kun** [comment] 2018-01-20 09:53
Not sure but, if a role of a user is higher then the role of the bot. It can't ban that person right?

**Comment by zergling-man** [comment] 2018-01-20 11:21
I believe so, so that part seems to be working as intended, except that it doesn't mark them as "invalid".
But it also doesn't even blacklist them, which I feel it should be doing anyway.

**Comment by Macley-Kun** [comment] 2018-01-23 16:51
Should this be marked as a bug Kwoth or do we call it a feature? 👀 ...

**Comment by Macley-Kun** [comment] 2018-02-11 12:42
I know this is a bit annoying to ask but. Can you maybe make a gif or show a bit more in depth what exactly goes wrong. 

The issue is on for a month almost. Think if we add more info we could get this fixed... I hope.

**Comment by Macley-Kun** [comment] 2018-02-12 10:38
Well if the users got banned afterwards, it might be just a hiccup with ratelimits i assume. It's up to you to keep this open.

I would've hoped other people would have the same problem but it seems like only you have bin affected by this one-time off bug.

**Comment by zergling-man** [comment] 2018-02-12 13:05
Technically, it was @Kwoth that was affected by the bug.
Ratelimits seem... Unlikely... I'm inclined to keep the issue open since it could well happen again, and on that offchance, I'd direct the reporter to this thread. Of course, I'm not a janitor for this place...

**Comment by Kwoth** [comment] 2018-02-12 14:14
Masskill does NOT work on public nadeko for whatever reason, and i don't know what's causing it, I'll look into it soon:tm:

**Comment by Midoriin** [comment] 2018-02-20 13:48
When I tried to masskill someone with ID, It was stuck, saying "in progress..."
Then I tried to masskill someone with their name and discriminator, it said "completed", but they werent banned from the server. Not sure if they were blacklisted or not.
![1](https://midorina.ga/u/5d06f42688ce.png)
![2](https://midorina.ga/u/996f5ba3f2bd.png)

**Comment by Kwoth** [comment] 2018-03-27 09:53
I fixed this a while back.

**Closed by Kwoth** 2018-03-27 09:53 UTC
