### ISSUE TITLE
.repeat isn't working properly

### ISSUE THREAD

**Issue by Akumy** [Kwoth/NadekoBot#1894] opened 2017-12-04 09:41 UTC
Hello,

im having an Issue with the .repeat command.
I wanted to set up a .repeat every 43 mins i used the following command  " .repeat 43 [text]" but it doesnt work properly.
Either its skipping one repeat , delaying the next (so it repeats after 58 mins for example instead of 43) or it just stops repeating and if i use the ".repeatlist" command there is a yellow triangle with an exclamation mark in it.

Im LF a fix regards.

**Comment by Macley-Kun** [comment] 2017-12-09 13:53
Can you show us some screenshots? We can try to replicate it and see if this bug appears to multiple people. We can then mark this as a bug for kwoth if it is.

**Comment by Macley-Kun** [comment] 2017-12-15 12:31
Update on this? Otherwise we assume you got it fixed :P ?

**Comment by Wizkiller96** [comment] 2017-12-17 08:31
Still is an issue from what I have seen. When you do .repeatlist it displays the warning triangle. As to what the yellow warning thing might mean. https://i.gyazo.com/cb63fcb8724d1c75382134a8bc6814d3.png

**Comment by Macley-Kun** [comment] 2017-12-19 10:23
@Kwoth you can close this. I assume he got it fixed

**Comment by MaybeGoogle** [comment] 2017-12-20 22:14
I mean, shards are still auto-restarting... so although the problem isn't fixed, there can't be much to do except maybe 
1. Get a smaller repeat interval
2. Fix memory problems and minimize restarts
3. Have some way to track when the repeat command was executed, and repeat based on that time instead. Only problem is that the bot may skip one if it's restarting when it needs to repeat.

**Comment by shikhir-arora** [comment] 2017-12-23 11:33
> I mean, shards are still auto-restarting... so although the problem isn't fixed, there can't be much to do except maybe

This is correct for the most part. `.repeat` requires keeping track of the prior message ID; this is not something Nadeko exclusive either: generally speaking when you restart a shard/bot, it has no recollection of the data unless you store it in a database and replicate that thru shard restarts but this starts a very convoluted process, because shard restarts aren't scheduled or normal events. 

I assume when you guys say it doesn't work you mean to say it doesn't delete the prior message it sent out. And yeah, that can look like it skipped one, depending on when it was closed.  I don't think there's much to be done about this; I've known about this on my (non-sharded) bot forever now - and it makes sense that Nadeko doesn't keep track of messages for repeat indexes on restart. I guess it could, but there would be a lot of checks that would have to go in play first.

**Comment by Kwoth** [comment] 2018-05-04 06:48
Yea should be fine now considering bot is stable now 😂

**Closed by Kwoth** 2018-05-04 06:48 UTC
Labels: to investigate
