### ISSUE TITLE
Issues With Nadeko-mute command

### ISSUE THREAD

**Issue by Frozone36** [Kwoth/NadekoBot#1785] opened 2017-10-31 05:30 UTC
Recently I've been having problems with the mute command. Whenever I would try to mute someone I would be faced with this error message everytime...
![unknown](https://user-images.githubusercontent.com/33244856/32208328-086fe2a8-bdbf-11e7-9a79-96457eedaada.png)
I dont know how to fix it all the roles and permissions are in order and working, no recent server name changes or anything of that accord. When @Zergling_man#4117 aka daddy diddly tried it using |e await client.add_roles(message.author,list(role for role in channel.server.roles if role.name=='Silenced')[0]) he confirmed that it worked when he tried it. All other bot mutes seem to work too. All the tested cases - it works with just about anything but Nadeko, no roles work with Nadeko despite everything being in order.

So I'm at a loss here on what to do.

#1719 #1556

**Comment by zergling-man** [comment] 2017-10-31 05:32
And, it only occurs on this server. Notably, this server has 150 roles and nearly 8k members, but I doubt those are causing it.

**Comment by Kwoth** [comment] 2017-10-31 06:54
duplicate of #1535

**Closed by Kwoth** 2017-10-31 06:54 UTC
