### ISSUE TITLE
Restart

### ISSUE THREAD

**Issue by LunarSera** [Kwoth/NadekoBot#1736] opened 2017-10-21 18:39 UTC
As usual I select option 3, then 1 when running Nadeko.
on v 2.0.0, however, when I type the die command, the bot doesn't restart itself. and I lack understanding of what I'm supposed to do to get .restart to work.

**Comment by Brramble** [comment] 2017-10-21 18:47
I can reproduce this too, it does not close the console

**Comment by Kwoth** [comment] 2017-10-21 19:01
O.o

Isn't it 3 then 2?

**Comment by LunarSera** [comment] 2017-10-21 19:03
1 makes it restart without updating. 2 updates every time.

**Comment by Kwoth** [comment] 2017-10-21 19:19
@samdivaio can you please look into this, I can confirm too, it doesn't restart.

**Comment by shikhir-arora** [comment] 2017-10-21 19:25
@Kwoth might have to do with the way this was done https://github.com/Kwoth/NadekoBot/commit/a12702fb68522513a0e6e6dffe67891c7e9b21e9#diff-a1a77cd0f41a1e8fbba5fac1f7770a7c as that's the only change to this command since 1.9.

**Comment by shikhir-arora** [comment] 2017-10-22 08:35
@Kwoth 

Fix here - pictures attached.

Ignore the above message by me, the issue is that when you use `.die` to restart, because you implemented a ShardCoordinator and cache of such in 2.0, it's actually creating a second idle process. You can watch redis: `redis-cli --slave`  and see what's happening: 

- `.restartshard` works fine, pushing a `_key + _shardcoord_restart shardID` event as usual
- `.die` (per Program.cs) creates a child process with the pid, shard ID (in this case 0) 
-  Killing this manually (for me on Linux, finding the dotnet processes: `ps aux | grep dotnet`) will see an *extra* process spawned from the parent process.
- If you try to rebuild or restart the project you'll get an error that it's being used at the moment: `
/usr/share/dotnet/sdk/2.0.0/Microsoft.Common.CurrentVersion.targets(4051,5): warning MSB3026: Could not copy "obj/Release/netcoreapp2.0/NadekoBot.dll" to "bin/Release/netcoreapp2.0/NadekoBot.dll". Beginning retry 5 in 1000ms. The process cannot access the file /home/vlexar/main/vlexar/NadekoBot/src/NadekoBot/bin/Release/netcoreapp2.0/NadekoBot.dll because it is being used by another process. 
`
- Killing it manually by the process ID of the parent (see pics below) will instantly trigger the pending `.die` command, however, with the current code it'll cause another shard to spawn as "dead" in the cache. You can see the output of a subsequent restart below with `.shardstats` 

- **The solution?** Revert to this logic: https://github.com/Kwoth/NadekoBot/blob/0bacb1f780198c842322aac8884bce2be4fd2ad9/src/NadekoBot/Program.cs and it will fix **both** the restart problem and the additional shard being spawned in redis cache. I have confirmed that it works as intended without any effects. 

<img width="804" alt="ss2" src="https://user-images.githubusercontent.com/8797918/31860025-4de95c4e-b6e2-11e7-81f2-95f80e233568.png">
<img width="842" alt="ss3" src="https://user-images.githubusercontent.com/8797918/31860026-51f725a0-b6e2-11e7-8d3d-c5315e72393d.png">
<img width="429" alt="ss4" src="https://user-images.githubusercontent.com/8797918/31860028-557ab84a-b6e2-11e7-9fa9-26b80baec2bf.png">

👍

**Comment by shikhir-arora** [comment] 2017-10-22 09:56
If anyone wants to confirm who are running `2.0.x` -- navigate to your `NadekoBot` folder, specifically: `NadekoBot/src/NadekoBot` and remove Program.cs (`rm Program.cs` or `rm NadekoBot/src/NadekoBot/Program.cs`). Then `wget https://raw.githubusercontent.com/Kwoth/NadekoBot/0bacb1f780198c842322aac8884bce2be4fd2ad9/src/NadekoBot/Program.cs` and hard-restart Nadeko. `.die` should work properly, and no ghost shards should be seen with `.shardstats`

**Comment by Brramble** [comment] 2017-10-22 11:39
@shikhir-arora Thank you it works

**Comment by shivaco** [comment] 2017-10-22 11:44
![image](https://user-images.githubusercontent.com/22858781/31861504-28927a48-b750-11e7-8192-e3c45dfc232e.png)
@shikhir-arora did that and even `Shard #0 is in Connected state` disappeared 
![image](https://user-images.githubusercontent.com/22858781/31861527-94995f22-b750-11e7-835a-0505ff824a92.png)

**Comment by shikhir-arora** [comment] 2017-10-22 12:29
Yeah although it’s still there and connecting - and updating Redis -  (`.restartshard 0`), but looks like it’s not sending the initial `RPUSH` which updates that menu and sets the key. I’ll take a look, but since it’s working @Kwoth may want to do this another way. It still publishes the guild update to redis properly and handles all of the other logic fine. This was the first thing that worked but it’s technically not a complete fix in that it doesn’t push the initial status out for the Shard. Haven’t had a big look at ShardCoordinator.

**Comment by Kwoth** [comment] 2017-10-22 14:11
Fixed in last push I think?

**Closed by Kwoth** 2017-10-22 14:11 UTC
Labels: bug

**Comment by shikhir-arora** [comment] 2017-10-22 14:19
Didn't realize at the time but I did say that it wasn't a fix in my last post. Anyways it's fixed, thanks. 👍
