### ISSUE TITLE
The imported project "C:\Program Files\dotnet\sdk\1.0.0-preview4-004233\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found.

### ISSUE THREAD

**Issue by raxixor** [Kwoth/NadekoBot#1006] opened 2017-01-26 03:06 UTC
I have installed the latest version of Nadeko.
This happens whenever I try to run Nadeko.

Quick Edit: The file does not exist on disk. I have checked.
Quick Edit 2: Nor do any of the folders after `1.0.0-preview4-004233`.

ERROR BELOW.
`D:\Programming\Discord Bot\Nadeko\NadekoBot\src\NadekoBot\NadekoBot.xproj(7,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\1.0.0-preview4-004233\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.`

**Comment by Garnet-D** [comment] 2017-01-26 04:23
My fix for the problem is to disable 1.0.0-preview4-004233 by renaming it x1.0.0-preview4-004233.
Also got: 1.0.0-preview2-1-003177, 1.0.0-preview2-1-003131, 1.0.0-preview2-1-003156 but those work fine.

**Comment by raxixor** [comment] 2017-01-26 04:33
That worked. Thanks.

**Comment by xnaas** [comment] 2017-01-26 18:01
@raxixor or @Kwoth, close the issue. 😛

**Closed** 2017-01-26 18:06 UTC
